### ISSUE TITLE
Encryptonize - storageless mode

### ISSUE THREAD

**Issue by matas-cc** [cyber-crypt-com/encryptonize-core#192]
The issue can be continuously updated and reevaluated.

**User story**
As an owner of the system that uses encryptonize
I want to use encryptonize as an object encryption service, that returns the ciphertext as a response
So that I can encrypt data, but place it in my own storage

**Acceptance Criteria**

- New features and changes are documented
- New service is added that provides gRPC endpoints in Encryptonize that encrypt and decrypt data.
- Code is refactored to better reflect the separation of services.
- The existing storage service and the new encryption service can be enabled/disabled on startup through configuration.
- Update ECCS? - to be seen

**Non-functional requirements**
Currently none. 
If time allows, existing benchmarking tests might be expanded to include the new service

**Additional context**
Decisions can be changed during development.

**Subtasks**
- [x] https://github.com/cyber-crypt-com/encryptonize-core/issues/193
- [x] https://github.com/cyber-crypt-com/encryptonize-core/issues/194
- [x] https://github.com/cyber-crypt-com/encryptonize-core/issues/195
- [x] https://github.com/cyber-crypt-com/encryptonize-core/issues/196
