### ISSUE TITLE
Add ECCS tests

### ISSUE THREAD

**Issue by iead-cc** [cyber-crypt-com/encryptonize-core#94]
**Description**
ECCS is often left behind when refactoring APIs like in PR #79 or when introducing new features.
To prevent ECCS from beeing left behind in the future we should add tests and tie them into the github pipeline

**Acceptance Criteria**
- All ECCS functions are tested
- Add new item in the PR template like '[ ] added functions for new features in ECCS'

**Scope**
Testing ECCS functionality

**Not in Scope**
creating e2e tests with ECCS

**Additional context**
Test alone don't garantie that ECCS is left behind when new features are introduced. Thats why a minor update to the PR template is necessary

**Tasks**
- [x] Add tests for ECCS functions
- [x] Integrate into CI workflow
- [ ] Add PR template item
